config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number', to: 'users#verify_phone_number'
      patch '/update_phone_number', to: 'users#update_phone_number'

    end
  end
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/your_trips', to: 'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve', to: "reservations#approve"
      post '/decline', to: "reservations#decline"
    end
  end

  get '/host_calendar', to: "calendars#host"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index: 4;">
  <%= link_to "Air Rooms", root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= form_tag search_path, method: :get do %>
          <div class="form-group <%= 'is-hidden' if current_page?(root_path)%>">
            <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: 'form-control'%>
          </div>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav mr-1">
      <li>
          <%= link_to "Become a host", new_room_path, class: "nav-item btn  btn-babu mr-3" %>
      </li>
      <% if user_signed_in?%>
      <%= image_tag avatar_url(current_user), class: "avatar"%>
      <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%if current_user.name.nil? %>
          <%= current_user.email%>
          <%else%>
          <%= current_user.name%>
          <%end%>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Dashoard", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Manage Your Listing", rooms_path, class: "dropdown-item" %>
          <%= link_to "List Your Place", new_room_path, class: "dropdown-item" %>
          <%= link_to "Your Reservation", your_reservations_path, class: "dropdown-item"%>
          <%= link_to "Your Trips", your_trips_path, class: "dropdown-item"%>
          <hr>
          <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>

    <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-secondary" %>

          <%= link_to "Log In", new_user_session_path, class: "btn btn-link" %>
      <% end %>
    </ul>
  </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}")%>
<nav class="navbar-default">
  <ul class="navbar-nav">
    <li <% if current_page?(dashboard_path) %>class="active" <%end%> ><%= link_to "Dashboard", dashboard_path %></li>
    <li <% if current_page?(rooms_path) %>class="active" <%end%>><%= link_to "Manage Listings", rooms_path %></li>
</ul>
</nav>
<% end %>

app/views/shared/_noty.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success')%>
      new Noty ({
        type: '<%= type %>',
        layout: 'topRight',
        timeout: '3000',
        theme: 'relax',
        text: '<%= value %>'
      }).show();
    <% end %>
  </script>
<%end%>