config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number', to: 'users#verify_phone_number'
      patch '/update_phone_number', to: 'users#update_phone_number'

    end
  end
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/your_trips', to: 'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve', to: "reservations#approve"
      post '/decline', to: "reservations#decline"
    end
  end

  get '/host_calendar', to: "calendars#host"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  enum status: {Waiting: 0, Approved: 1, Declined: 2}

  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:approve, :decline]

  def create
    room = Room.find(params[:room_id])

    if current_user == room.user
      return redirect_to room, alert: "You cannot book your own property!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = (end_date - start_date).to_i + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price
      @reservation.total = room.price * days

      if @reservation.save

        if room.Request?
          flash[:notice] = "Request sent successfully"
        else
          @reservation.Approved!
          flash[:notice] = "Reservation sent successfully"
        end
      else
        flash[:alert] = "Cannot make a reservation!"
      end
    end
    redirect_to room
  end

  def your_trips
    @trips = current_user.reservations.order(start_date: :asc)
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  def approve
    @reservation.Approved!
    redirect_to your_reservations_path

  end

  def decline
    @reservation.Declined!
    redirect_to your_reservations_path

  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])

    end
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date, :guest)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading p-2">
    <span><% if @room.Instant? %><i class="fas fa-bolt" style="color: #ffd100;"></i><% end %> <i class="fas fa-dollar-sign"></i><%= @room.price %></span>
    <span class="float-right">Per Night</span>
  </div>
  <div class="panel-body">
    <%= form_for([@room, @room.reservations.new]) do |f| %>
      <div class="row mt-2">
        <div class="col-md-6">
          <label>Check In</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>Check Out</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "End Date", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <div class="form-group">
          <%= f.select :guest, [['1', 1], ["2", 2], ["3", 3], ["4", 4], ["4+", 4], ["5", 5], ["6", 6], ["7", 7]], prompt: "Guest...", class: 'form-control'%>
        </div>
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Price</td>
              <td class="text-right">$<%= @room.price %></td>
            </tr>
            <tr>
              <td>Night(s)</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">$<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>
      <% if @room.Instant? %>
        <%= f.submit "Book Now", id: "btn_book", class: "btn btn-danger btn-block", disabled: true %>
      <% else %>
        <%= f.submit "Request Now", id: "btn_book", class: "btn btn-danger btn-block", disabled: true %>
      <% end %>
    <% end %>
  </div>
</div>

<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_room_path(@room) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            $('#reservation_end_date').attr("disabled", false);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });

          }
        });

        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });



  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row mx-3">
  <div class="col-md-3 col-12">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your Listing", rooms_path, class: 'sidebar-link'%>
      </li>

      <li class="sidebar-item">
        <%= link_to "Your Reservations", rooms_path, class: "sidebar-link active"%>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your Trips", your_trips_path, class: 'sidebar-link'%>
      </li>
    </ul>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading p-2">
        Your Reservations
      </div>
      <div class="panel-body">
        <% @rooms.each do |room|%>
          <% room.reservations.each do |reservation|%>
            <div class="row mt-3">
              <div class="col-md-2">
                <%= reservation.start_date.strftime('%v')%>
                <p><%= reservation.status %></p>
                <div class="form-inline">
                  <% if reservation.Waiting? %>
                    <%= link_to "Approve", approve_reservation_path(reservation), method: :post, class: "text-babu" %> |
                    <%= link_to "Decline", decline_reservation_path(reservation), method: :post, class: "text-babu" %>
                  <% end %>
                </div>
              </div>
              <div class="col-md-2">
                <%= link_to room_path(reservation.room) do %>
                  <%= image_tag reservation.room.cover_photo(:thumb)%>
                <% end %>
              </div>
              <div class="col-md-6">
                <%= link_to reservation.room.listing_name, room_path(reservation.room)%>
                <span class="float-right">
                  <%= link_to user_path(reservation.user) do %>
                  <%= image_tag avatar_url(reservation.user), class: 'avatar-large'%><br />
                  <%= reservation.user.name %>
                  <% end %>
                </span>
              </div>
              <div class="col-md-2">
                <% if reservation.Approved? && reservation.end_date < Date.today %>
                 <%= render partial: "reviews/host_form", locals: {reservation: reservation}  %>
                 <% end %>
              </div>
            </div>
            <hr >
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row mx-3">
  <div class="col-md-3 col-12">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your Listing", rooms_path, class: 'sidebar-link'%>
      </li>

      <li class="sidebar-item">
        <%= link_to "Your Reservations", rooms_path, class: "sidebar-link"%>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your Trips", your_trips_path, class: 'sidebar-link active'%>
      </li>
    </ul>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading p-2">
        Your Trips
      </div>
      <div class="panel-body">
        <% @trips.each do |trip| %>
        <div class="row mt-3">
          <div class="col-md-2">
            <%= trip.start_date.strftime('%v') %>
            <%= trip.status %>
          </div>
          <div class="col-md-2">
            <%= link_to room_path(trip.room) do %>
              <%= image_tag trip.room.cover_photo(:thumb) %>
            <% end %>
          </div>
          <div class="col-md-6">
            <%= link_to trip.room.listing_name, room_path(trip.room) %>
            <span class="float-right text-center">
              <%= image_tag avatar_url(trip.room.user), class: 'avatar-large'%><br >
              <%= link_to user_path(trip.room.user) do %>
                <%= trip.room.user.name %>
              <% end %>
            </span>

          </div>
          <div class="col-md-2">
            <% if trip.Approved? && trip.end_date < Date.today %>
            <%= render partial: "reviews/guest_form", locals: {reservation: trip} %>
            <% end %>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>