config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number', to: 'users#verify_phone_number'
      patch '/update_phone_number', to: 'users#update_phone_number'

    end
  end
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/your_trips', to: 'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve', to: "reservations#approve"
      post '/decline', to: "reservations#decline"
    end
  end

  get '/host_calendar', to: "calendars#host"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}


  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :guest_reviews


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true, length: { maximum: 200 }
  validates :room_type, presence: true, length: { maximum: 100 }
  validates :accommodate, presence: true
  validates :bed_room, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 10 }
  validates :bath_room, presence: true, numericality: { only_integer: true, greater_than: 0}

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "room_cover.jpg"
    end

  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @room.reservations.where("(start_date >= ? OR end_date >= ?) AND status = ?", today, today, 1)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("(? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
      check.size > 0? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :instant)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list ml-5">
  <li class="sidebar-item ">
    <%= link_to "Listing", listing_room_path, class: 'sidebar-link active'%>
    <% if !@room.home_type.blank? && !@room.room_type.blank? && !@room.accommodate.blank? && !@room.bed_room.blank? && !@room.bath_room.blank?%>
    <span class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">

    <%= link_to "Pricing", pricing_room_path, class: 'sidebar-link active'%>
    <% if !@room.price.blank? && @room.price != 0 %>
    <span class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: 'sidebar-link active'%>
    <% if !@room.summary.blank? && !@room.listing_name.blank? %>
    <span class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: 'sidebar-link active'%>
    <% if !@room.photos.blank? %>
    <span id="photo_check" class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: 'sidebar-link active'%>
    <% if !@room.is_tv.blank? || !@room.is_air.blank? || !@room.is_heating.blank? || !@room.is_kitchen.blank? || !@room.is_internet.blank?%>
    <span class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: 'sidebar-link active'%>
    <% if !@room.address.blank? %>
    <span class="float-right text-babu pr-3"><i class="fas fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr >
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? && !@room.home_type.blank? && !@room.room_type.blank? && !@room.accommodate.blank? && !@room.bed_room.blank? && !@room.bath_room.blank?  %>
<%= form_for @room do |f|%>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: 'btn btn-danger btn-lg btn-block', disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= link_to room do %>
          <%= image_tag room.cover_photo(:medium) %>
          <% end %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= room.id %>').raty({
        path: 'https://cdnjs.cloudflare.com/ajax/libs/raty/2.8.0/images/',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Amenities
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f|%>
          <div class="row form-group mt-3">
            <div class="col-md-2">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="col-md-2">
              <%= f.check_box :is_air %> Aircon
            </div>
            <div class="col-md-2">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="col-md-2">
              <%= f.check_box :is_internet %> Internet
            </div>
            <div class="col-md-2">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
          </div>
            <br>
          <div class="row"><%= f.submit "Save", class: 'btn-babu z-depth-1a' %></div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Description
      </div>
      <div class="panel-body">
        <div class="container mt-3">
          <%= form_for @room do |f|%>
          <div class="row">
            <div class="form-group col-md-10">
              <label for="">Listing Name</label>
              <%= f.text_field :listing_name, placeholder: "Mountain view house", class: "form-control", required: true%>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-10">
              <label for="">Summary</label>
              <%= f.text_area :summary, placeholder: "Nice tiny house on the tree with mountain view", class: "form-control", required: true%>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: 'btn-babu'%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row mx-3">
  <div class="col-md-3 col-12">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your Listing", rooms_path, class: 'sidebar-link active'%>
      </li>

      <li class="sidebar-item">
        <%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link"%>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your Trips", your_trips_path, class: 'sidebar-link'%>
      </li>
    </ul>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listing
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
        <div class="row mt-3">
          <div class="col-md-2 col-12">
            <%= image_tag room.cover_photo(:thumb) %>
          </div>
          <div class="col-md-7">
            <h4><%= room.listing_name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "Update", listing_room_path(room), class: 'btn-babu'%>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading p-3">
        Listing
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f|%>
          <div class="row mt-3">
            <div class="col-12 col-md-4 select">
              <div class="form-group">
                <label for="">Home Type</label>
                <%= f.select :home_type, [['Apartment', 'Apartment'], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                id: 'home_type', prompt: "Select...", class: 'form-control', required: true %>
              </div>
            </div>
            <div class="col-12 col-md-4 select">
              <div class="form-group">
                <label for="">Room Type</label>
                <%= f.select :room_type, [['Entire', 'Entire'], ["Private", "Private"], ["Shared", "Shared"]],
                id: 'room_type', prompt: "Select...", class: 'form-control', required: true%>
              </div>
            </div>
            <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Booking Type</label>
              <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, selected: 'Instant', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>

            <div class="col-12 col-md-4 select">
              <div class="form-group">
                <label for="">Accommodate</label>
                <%= f.select :accommodate, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                id: 'accommodate', prompt: "Select...", class: 'form-control', required: true%>
              </div>
            </div>

            <div class="col-12 col-md-4 select">
              <div class="form-group">
                <label for="">Bedrooms</label>
                <%= f.select :bed_room, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                id: 'bed_room', prompt: "Select...", class: 'form-control', required: true%>
              </div>
            </div>

            <div class="col-12 col-md-4 select">
              <div class="form-group">
                <label for="">Bathrooms</label>
                <%= f.select :bath_room, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                id: 'bath_room', prompt: "Select...", class: 'form-control', required: true%>
              </div>
            </div>
          </div>
          <div><%= f.submit "Save", class: 'btn-babu' %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Location
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f|%>
          <div class="row mt-3">
            <div class="form-group col-md-10">
              <label for="">Address</label>
              <%= f.text_field :address, placeholder: "123, 14 Street, Herndon VA 22071-2716", class: "form-control", required: true%>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: 'btn-babu'%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    List your beautiful place for rent
  </div>
  <div class="panel-body">
    <div class="container">
      <div class="text-danger"><h3>Please fill in all fileds</h3></div>
      <%= form_for @room do |f|%>
        <div class="row">
          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Home Type</label>
              <%= f.select :home_type, [['Apartment', 'Apartment'], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                  id: 'home_type', prompt: "Select...", class: 'form-control', required: true %>
            </div>
          </div>
          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Room Type</label>
              <%= f.select :room_type, [['Entire', 'Entire'], ["Private", "Private"], ["Shared", "Shared"]],
                  id: 'room_type', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>
          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Booking Type</label>
              <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, selected: 'Instant', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>

          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Accommodate</label>
              <%= f.select :accommodate, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                  id: 'accommodate', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>

          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Bedrooms</label>
              <%= f.select :bed_room, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                  id: 'bed_room', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>

          <div class="col-12 col-md-4 select">
            <div class="form-group">
              <label for="">Bathrooms</label>
              <%= f.select :bath_room, [['1', 1], ["2", 2], ["3", 3], ["4+", 4]],
                  id: 'bath_room', prompt: "Select...", class: 'form-control', required: true%>
            </div>
          </div>
        </div>
        <div><%= f.submit "Create A Room", class: 'btn btn-warning' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Photos
      </div>
      <div class="panel-body">
        <div class="container mt-3">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- photos upload goes here -->
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f|%>
              <div class="row mt-3 col-md-10 col-12">
                <div class="form-group">
                  <span class="btn btn-outline-secondary btn-file text-center"><i class="fas fa-images"></i>
                    Select Photos
                    <%= file_field_tag "images[]", type: :file, multiple: true %>
                  </span>
                </div>
              </div>
              <div class="text-center">
                <%= f.submit "Add Photos", class: 'btn-babu'%>
              </div>
              <% end %>
            </div>
          </div>
          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3 col-12">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9 col-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Pricing
      </div>
      <div class="panel-body">
        <div class="container mt-3">
          <%= form_for @room do |f|%>
          <div class="row">
            <div class="form-group">
              <label for="">Price $USD</label>
              <%= f.text_field :price, placeholder: "100", class: "form-control", required: true %>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: 'btn-babu'%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!--Cover Image-->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= image_tag @room.cover_photo(nil), width: " 100%"%>
    </div>
  </div>
  <br />

  <div class="row">
    <!--Left-->
    <div class="col-md-8">
      <!--Listing name-->
      <div class="row">
        <div class="col-md-8">
          <h1><%= @room.listing_name %></h1>
          <%= @room.address %>
        </div>
        <div class="col-md-4 text-center">
          <%= image_tag avatar_url(@room.user), class: 'avatar-large-bordered'%><br/>
          <%= @room.user.name%>
        </div>

      </div>
      <hr>
      <!--Room Info-->
      <div class="row flex-column text-babu ">
        <div class="row text-center row-space-1">
          <div class="col-md-3">
            <i class="fas fa-door-open fa-2x"></i>
          </div>
          <div class="col-md-3">
            <i class="fas fa-users fa-2x"></i>
          </div>
          <div class="col-md-3">
            <i class="fa fa-bed fa-2x"></i>
          </div>
          <div class="col-md-3">
            <i class="fa fa-bath fa-2x"></i>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-3"><%= @room.home_type.capitalize %></div>
          <div class="col-md-3"><%= pluralize(@room.accommodate, "Guest") %></div>
          <div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
          <div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
        </div>
      </div>
      <hr>
      <!--Description-->
      <div class="row">
        <div class="col-md-3">
          <h4>Description</h4>
        </div>
        <div class="col-md-9">
          <p><%= @room.summary%></p>
        </div>
      </div>
      <hr>
      <!--Amenities-->
      <div class="row amenities">
        <div class="col-md-3">
          <h4>Amenities</h4>
        </div>
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-6">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </div>
            <div class="col-md-6">
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
            </div>
          </div>
        </div>

      </div>
      <hr>
      <!--Carousel photos-->
      <div class="row">
        <div class="col-md-3">
          <h4>Photos Slide</h4>
        </div>
        <div class="col-md-9">
          <% if @photos.length > 0 %>
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>
            <div class="carousel-inner">
              <% @photos.each do |photo| %>
              <div class="carousel-item <%= 'active' if photo.id == @photos[0].id %>">
                <%= image_tag photo.image.url(:medium), class: 'd-block w-100' %>
              </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <% end %>
        </div>
      </div>
      <hr>
      <!--reviews-->
      <div class="row">
        <div class="col-md-12">
          <h3><%= pluralize(@guest_reviews.count, "Review")%>
            <span id="average_rating"></span>
          </h3>
          <div class="container">
            <div><%= render 'reviews/guest_list'%></div>
          </div>
        </div>
        <hr >
      </div>
      <!--Map-->
      <div class="row mt-3">
        <div id="map" style="width: 100%; height: 400px"></div>
        <script src="https://maps.googleapis.com/maps/api/js"></script>
        <script>
          function initialize() {
            var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
            center: location,
            zoom: 14
          });

          var marker = new google.maps.Marker({
            position: location,
            map: map
          });

          var contentString = '<div id="content">'+'<%= image_tag @room.cover_photo(:medium) %>'+'</div>';

          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });

         infowindow.open(map, marker);
        }

        google.maps.event.addDomListener(window, 'load', initialize);
        </script>

      </div>
      <hr >

      <!--Nearby Rooms-->
      <div class="row flex-column">
        <h4>Rooms Near by</h4>
        <div class="row">
          <% for room in @room.nearbys(10) %>
          <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.cover_photo(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room, :"data-turbolinks" => false %><br >
              (<%= room.distance.round(2) %> kms away)
            </div>
          </div>
        </div>
        <% end %>
        </div>

      </div>

    </div>
    <!--Right-->
    <div class="col-md-4">
    <!-- Reservation Form -->
      <%= render 'reservations/form' %>
    </div>
  </div>
</div>

<script>
  $('#average_rating').raty({
      path: 'https://cdnjs.cloudflare.com/ajax/libs/raty/2.8.0/images/',
      readyOnly: true,
      score: <%= @room.average_rating %>
    });
</script>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>